//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace faceplateio
{
    using System;
    using System.Collections.Generic;
    
    public partial class Script
    {
        public int Id { get; set; }
        public string From { get; set; }
        public string To { get; set; }
        public string Message { get; set; }
        public int Owner { get; set; }
        public Nullable<int> Wait_Delay { get; set; }
        public Nullable<System.DateTime> Wait_Time { get; set; }
        public Nullable<int> Exit_Wait { get; set; }
        public Nullable<int> Next_Button { get; set; }
        public string Key { get; set; }
        public string Wait_Confirm { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
    }
}
