//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace faceplateio
{
    using System;
    using System.Collections.Generic;
    
    public partial class Step
    {
        public int Id { get; set; }
        public Nullable<int> Account { get; set; }
        public string Label { get; set; }
        public Nullable<int> Operator { get; set; }
        public Nullable<int> Operand { get; set; }
        public Nullable<int> Operant { get; set; }
        public Nullable<int> Mode { get; set; }
        public string Data { get; set; }
        public Nullable<int> EQ { get; set; }
        public Nullable<int> GT { get; set; }
        public Nullable<int> LT { get; set; }
        public Nullable<int> NULL { get; set; }
    }
}
